modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/ochotonida/curious-armor-stands/issues"
license="MIT"

[[mods]]
modId="curious_armor_stands"
version="${file.jarVersion}"
displayName="Curious Armor Stands"
displayURL="https://www.curseforge.com/minecraft/mc-mods/curious-armor-stands"
logoFile="logo.png"
description='''Allows armor stands to display curios'''

[[dependencies.curious_armor_stands]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.curious_armor_stands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.curious_armor_stands]]
    modId="curios"
    mandatory=true
    versionRange="[1.18.1-5.0.4.0,)"
    ordering="NONE"
    side="BOTH"